### ISSUE TITLE
Video Messages

### ISSUE THREAD

**Issue by trymeouteh** [oxen-io/session-android#432] opened 2021-02-06 03:00 UTC
Please allow for the ability to send video messages. Same thing as the audio messages were you tap the record button, record and then  tap send except this for video. Videos can be low res and have a limit on their length like 30 seconds or something.

**Comment by hjubb** [comment] 2022-05-02 04:17
I think this is a duplicate of #392 will track it there

**Closed by hjubb** 2022-05-02 04:17 UTC
Labels: feature-request
