### ISSUE TITLE
[Feature + Idea] Making able to send and receive unlimited size of files

### ISSUE THREAD

**Issue by User1l0** [oxen-io/session-android#1172] opened 2023-05-02 12:23 UTC
Making this possible can done by splitted file transfer.
How much i know the limit of session files is 8 megs because of limited loki network abilities.
Resolving this issue can be done by allowing session to send for example a gigabyte of file by allowing the messenger to split the huge file to parts for example couple of 8 megs parts of data, and sending it to receiver(s) session messenger that is going to pack the splitted data together and making the huge file ready to use.

I hope this idea can be implemented in the future to the session messenger, by making session more powerful and popular messenger to use. Thank You.

**Comment by tashijayla** [comment] 2023-05-02 17:57
Session is not using Lokinet at the moment. Session is using onion request. Once Lokinet is integrated into Session you will be able to send any size file, the only question is what size files will people have to pay extra to send when Session premium comes out.
Splitting Large files into lots of small packets of data in my opinion will just make it take longer to send and to download, thanks for trying to find a solution to the problem that at the moment the file size is so small but it won't be needed most likely when full Lokinet is integrated

**Comment by ElsAr4e** [comment] 2023-05-03 13:25
> Session premium

At least it would be better if you're going to have two different apps: Regular Session and Session Premium (paid).

I don't want to have session with In-App Purchase or even with ads. But that's probably another issue.

**Comment by tashijayla** [comment] 2023-05-03 17:50
> > Session premium
> 
> At least it would be better if you're going to have two different apps: Regular Session and Session Premium (paid).
> 
> I don't want to have session with In-App Purchase or even with ads. But that's probably another issue.



Session is completely open source, I think you will find that open source apps don't tend to have ads and Session is no different, so don't worry

**Comment by keybreak** [comment] 2023-10-23 11:24
> Unlimited weight (mb) is not possible for security reason (flood attacks).

Maybe it is technically possible, if you're using bittorrent style of protocol to redistribute small pieces of file between seeds on Lokinet...then such pieces would be downloaded -> Assembled -> decrypted... :thinking:

**Comment by KeeJef** [comment] 2023-11-13 04:55
Closing this as a duplicate of https://github.com/oxen-io/session-android/issues/267

**Closed by KeeJef** 2023-11-13 04:55 UTC
