### ISSUE TITLE
Reject/accept option for DMs

### ISSUE THREAD

**Issue by Flam3z** [oxen-io/session-android#770] opened 2021-10-14 05:11 UTC
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

Im sick of random strangers dming me from groups, please add a feature like telegram where i can choose to block or decline their dm ty.

**Comment by Flam3z** [comment] 2021-10-18 00:42
omg tysm, love you.

**Comment by sierra0scar** [comment] 2021-11-08 09:49
And add block to that as well... Accept/Reject/Reject and block

**Comment by Sepero** [comment] 2021-11-29 04:06
Duplicate of #665

**Closed** 2021-11-29 05:26 UTC
Labels: bug

**Comment by sierra0scar** [comment] 2021-11-30 02:04
And.. Can we (in settings) - have an option to have allow/dissallow DM's
