### ISSUE TITLE
No way to get users public key in private chat

### ISSUE THREAD

**Issue by KeeJef** [oxen-io/session-android#265] opened 2020-07-20 06:59 UTC
If i add friend A using his public key, i can begin an conversation with them happily, but for example if i wanted friend A's public key to Friend B, There actually isn't any way i can see in the application to copy the person you are talking to's public key (You can copy public keys in Session open groups already, but not in person to person chats). We should add this

**Comment by gitmaker032** [comment] 2020-07-20 08:47
In addition to the ability to copy the public key from the top panel/menu inside the chat, I think the following functionality is needed:

1. Сopy or share friend's Session ID under a long press in the chat list (in the same menu where you can delete the chat). This will eliminate the need to go into the chat to copy the public key. 

2. "Contacts" section with the same functionality (to see everyone, even with whom there is no chat). There is such a section on the desktop version.

**Comment by beantaco** [comment] 2020-07-20 23:05
This looks like a duplicate of #254.

**Comment by beantaco** [comment] 2021-02-13 03:22
The feature proposed by @KeeJef has been added. In a session with another user, you can copy that user's Session ID.

The long press proposal by @gitmaker032 has been added. After a long press, a menu appears that shows copy, block and delete.

I think this issue should be closed.

**Closed** 2023-02-07 06:46 UTC
