### ISSUE TITLE
Make Button "Clear All Mesage in Dialog"

### ISSUE THREAD

**Issue by ghost** [oxen-io/session-android#531] opened 2021-05-09 13:57 UTC
It would be nice to have a button to clear all messages in the dialog.

**Comment by nielsandriesse** [comment] 2021-05-23 23:23
Hi @xbvrhlmb, which dialog is this?

**Comment by xbvrhlmb** [comment] 2021-05-24 22:20
> Hi @xbvrhlmb, which dialog is this?

Hi, if i open chat to user (dialog window)  i see chat message but if I need to delete messages, I need to delete each message in turn.

It would be great to have a button that deletes all the message in the chat with that user

**Comment by nielsandriesse** [comment] 2021-05-25 03:10
I see what you mean now! This is on our to do list :) .

**Comment by xbvrhlmb** [comment] 2021-10-01 11:38
@nielsandriesse  Thanks i see, you make this for desktop version
I hope this will also be done on the phone version)

**Comment by gitbq** [comment] 2022-10-03 10:12
Hi. Just wondering if there were any updates on this feature?  :)

**Comment by KeeJef** [comment] 2022-12-16 03:40
closing as duplicate of #497

**Closed by KeeJef** 2022-12-16 03:40 UTC
Labels: feature-request
