### ISSUE TITLE
Selfdestructed messages are stored in the swarm

### ISSUE THREAD

**Issue by noghx** [oxen-io/session-android#564] opened 2021-05-24 23:03 UTC
Messages send with selfdestruction timer are still stored in the swarm and can be restored with Seed.

Imagine your in a chinese police station and they force you to give your seed.

**Comment by nielsandriesse** [comment] 2021-05-24 23:14
This is a duplicate of #535 .

**Closed by nielsandriesse** 2021-05-24 23:14 UTC
Labels: bug

**Comment by noghx** [comment] 2021-05-24 23:31
No its duplicate of #407

**Comment by noghx** [comment] 2021-05-24 23:32
Fix it
