### ISSUE TITLE
Can't get User ID in Closed Groups

### ISSUE THREAD

**Issue by Sepero** [oxen-io/session-android#649] opened 2021-07-09 07:22 UTC
Can no longer get a users ID in Closed Groups.

Oxygen OS 10.3.5 (Android 10)
Session 1.11.2

**Comment by Norbert80** [comment] 2021-07-10 10:56
This one is a duplicate of
https://github.com/oxen-io/session-android/issues/517
where a proper solution similar to Session Desktop (clicking on avatars) is requested.

**Comment by nielsandriesse** [comment] 2021-07-12 04:30
We added back this feature. Adding the ability to click on profile pictures is in the pipeline. Closing this issue :)

**Closed by nielsandriesse** 2021-07-12 04:30 UTC
