### ISSUE TITLE
Clock out of sync Error

### ISSUE THREAD

**Issue by johhonn** [oxen-io/session-android#400] opened 2021-01-14 03:28 UTC
**Describe the bug**
I cannot send messages but I can receive them. I get the error message "you clock is out of sync with the service node network".
I have tried on both Wifi and 4g lte.

**To reproduce**
Download application from the google play store. Sign in and try send messages.

**Smartphone (please complete the following information):**

 - Device:Samung Galaxy S10e
 - OS: Android 10
 -  1.6.7.1

**Comment by froggobaggins** [comment] 2021-01-23 04:46
Same issue here, the error message stays on the screen until a restart on the phone. 

App v1.6.10 
Pixel 4a
Android 11
![Screenshot_20210122-233948](https://user-images.githubusercontent.com/48557443/105569007-fe747300-5d0b-11eb-99d8-85297e0d7770.png)

**Comment by KeeJef** [comment] 2021-03-02 02:41
This typically happens because the timestamp attached to the small PoW on each message deviates significantly from the clock time of the Service Node it is speaking to. This can be caused by either the Service Node's clocking being out of sync or the client devices clock being out of sync, we are looking at some fixes to better sync Service Node clock time, but it is useful to also check your devices clock time is being synced from the network to ensure its set accurately.

**Comment by nielsandriesse** [comment] 2021-05-23 23:43
This should be fixed now.

**Closed by nielsandriesse** 2021-05-23 23:43 UTC
Labels: bug
