### ISSUE TITLE
press enter to send option does not work in android session for both playstore and fdroid

### ISSUE THREAD

**Issue by holequantum** [oxen-io/session-android#928] opened 2022-07-19 19:23 UTC
**Code of conduct**

- [x ] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

sending massages with enter key does not work whether it is turned on or off it does not work.
**To reproduce**

open session and go to settings->chats->enter key send option turn that on 

**Smartphone (please complete the following information):**

 - Device: pixel 5xl and moto edge 20 pro and asus rog 5 xiaomi and moto one and some other devices that i have tried before to confirm the bug
 - OS: android 12 11 10
 - Version of Session or latest commit hash
1.13.6(2875)

**Comment by hjubb** [comment] 2022-07-19 23:54
This one is a duplicate of #846 and will be fixed shortly :+1:

**Closed by hjubb** 2022-07-19 23:54 UTC
Labels: bug
