### ISSUE TITLE
Sending multiple images fails. 

### ISSUE THREAD

**Issue by Lucifer1903** [oxen-io/session-android#784] opened 2021-10-31 22:58 UTC
**Code of conduct**

- [ x ] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

Sending multiple images doesn't work. 

**To reproduce**

Open session, select images, select multiple images (30 images), send. 
Session will show that it is trying to send the images but never finishes. Recipient does not receive any of the images. 

**Screenshots or logs**

If applicable, add screenshots or logs to help explain your problem.

**Smartphone (please complete the following information):**

 - Device: Huawei 
 - OS: Android 10
 - Version of Session: 1.11.11 (2295)

**Comment by KeeJef** [comment] 2023-02-07 03:51
I'm assuming this is running into the file size limitation but not reporting an error back to the user

**Comment by simophin** [comment] 2024-05-14 07:30
Hey @KeeJef I haven't been able to reproduce this issue. Tried to send 32 images and it went ok, albeit a bit slow. Waited on the screen for around 5min and the message was sent successfully. The attachment upload is done one by one that's why it's slow. The message won't be sent until all the attachments are uploaded.

We can probably try to upload the images concurrently to speed up the process, if that's something we prefer.

Also we don't really limit the total size of the attachment in one message, not sure if it's a bug or an intended behavior.

**Comment by bemusementpark** [comment] 2024-05-14 08:42
This issue appears to be ancient history: `Version of Session: 1.11.11 (2295)`  Nov 1, 2021

**Comment by Lucifer1903** [comment] 2024-05-14 09:03
Yeah, this was a long time ago. I'm just wondering how does the upload of multiple photos and sending to recipient handle network dropout?

If you send 10 photos 7 get uploaded and then you lose connection will session be able to continue uploading the remaining 3 and send the message once session has a connection again?

Also from a user perspective it would be good to see how many of the photos have been uploaded as it's happening.

**Comment by bemusementpark** [comment] 2024-05-14 09:26
> Yeah, this was a long time ago. I'm just wondering how does the upload of multiple photos and sending to recipient handle network dropout?

Some number of `AttachmentUploadJob`s is added for each attachment in `MessageSendJob`... That Job will return and it looks like it's resumed on successful attachment upload in `AttachmentUploadJob`

> If you send 10 photos 7 get uploaded and then you lose connection will session be able to continue uploading the remaining 3 and send the message once session has a connection again?

I don't know exactly, but there's some Jobs, and they'll retry som1e number of times, you can also manually resend e.g. in message details, or long-pressing a failed message.

> Also from a user perspective it would be good to see how many of the photos have been uploaded as it's happening.

Yeah, that'd be cool, at least on the message details screen. Or even a total % progress.

**Comment by KeeJef** [comment] 2024-05-14 23:18
Sounds like this issue is no longer reproducible, so I'll close it. However, as noted in previous comments, we should probably make some changes to the attachment UI to better indicate upload progress. This can be raised as a new ticket/issue.

**Closed by KeeJef** 2024-05-14 23:18 UTC
Labels: bug, good-first-issue

**Comment by KeeJef** [comment] 2024-05-14 23:24
The upload progress idea is being tracked via the following internal ticket SES-747
