### ISSUE TITLE
Session crashes at launching

### ISSUE THREAD

**Issue by d4f5409d** [oxen-io/session-android#1382] opened 2023-12-23 22:44 UTC
### Current Behavior

The app crashes.

### Expected Behavior

Open the app

### Steps to reproduce

Download Session F-Droid variant (without Google blobs)

Open it

Experience the error

### Android version

13

### Session version

1.17.5 - Fdroid

### Additional infos

Crash report: 
```FATAL EXCEPTION: main
Process: network.loki.messenger.fdroid, PID: 21760
java.lang.RuntimeException: Unable to create application org.thoughtcrime.securesms.ApplicationContext: android.database.sqlite.SQLiteException: file is not a database (code 26): , while compiling: SELECT COUNT(*) FROM sqlite_schema;
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7268)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2296)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8427)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
Caused by: android.database.sqlite.SQLiteException: file is not a database (code 26): , while compiling: SELECT COUNT(*) FROM sqlite_schema;
	at net.zetetic.database.sqlcipher.SQLiteConnection.nativePrepareStatement(Native Method)
	at net.zetetic.database.sqlcipher.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:925)
	at net.zetetic.database.sqlcipher.SQLiteConnection.executeForLong(SQLiteConnection.java:627)
	at net.zetetic.database.sqlcipher.SQLiteConnection.open(SQLiteConnection.java:239)
	at net.zetetic.database.sqlcipher.SQLiteConnection.open(SQLiteConnection.java:201)
	at net.zetetic.database.sqlcipher.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:474)
	at net.zetetic.database.sqlcipher.SQLiteConnectionPool.open(SQLiteConnectionPool.java:189)
	at net.zetetic.database.sqlcipher.SQLiteConnectionPool.open(SQLiteConnectionPool.java:181)
	at net.zetetic.database.sqlcipher.SQLiteDatabase.openInner(SQLiteDatabase.java:1028)
	at net.zetetic.database.sqlcipher.SQLiteDatabase.open(SQLiteDatabase.java:1013)
	at net.zetetic.database.sqlcipher.SQLiteDatabase.openDatabase(SQLiteDatabase.java:840)
	at net.zetetic.database.sqlcipher.SQLiteDatabase.openDatabase(SQLiteDatabase.java:740)
	at org.thoughtcrime.securesms.database.helpers.SQLCipherOpenHelper.open(SQLCipherOpenHelper.java:157)
	at org.thoughtcrime.securesms.database.helpers.SQLCipherOpenHelper.migrateSqlCipher3To4IfNeeded(SQLCipherOpenHelper.java:217)
	at org.thoughtcrime.securesms.dependencies.DatabaseModule.provideOpenHelper(DatabaseModule.kt:35)
	at org.thoughtcrime.securesms.dependencies.DatabaseModule_ProvideOpenHelperFactory.provideOpenHelper(DatabaseModule_ProvideOpenHelperFactory.java:39)
	at org.thoughtcrime.securesms.DaggerApplicationContext_HiltComponents_SingletonC$SingletonCImpl$SwitchingProvider.get(DaggerApplicationContext_HiltComponents_SingletonC.java:1471)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
	at org.thoughtcrime.securesms.DaggerApplicationContext_HiltComponents_SingletonC$SingletonCImpl$SwitchingProvider.get(DaggerApplicationContext_HiltComponents_SingletonC.java:1468)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
	at org.thoughtcrime.securesms.DaggerApplicationContext_HiltComponents_SingletonC$SingletonCImpl.injectApplicationContext2(DaggerApplicationContext_HiltComponents_SingletonC.java:1443)
	at org.thoughtcrime.securesms.DaggerApplicationContext_HiltComponents_SingletonC$SingletonCImpl.injectApplicationContext(DaggerApplicationContext_HiltComponents_SingletonC.java:1298)
	at org.thoughtcrime.securesms.Hilt_ApplicationContext.hiltInternalInject(Hilt_ApplicationContext.java:50)
	at org.thoughtcrime.securesms.Hilt_ApplicationContext.onCreate(Hilt_ApplicationContext.java:41)
	at org.thoughtcrime.securesms.ApplicationContext.onCreate(ApplicationContext.java:214)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1285)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7261)
	... 9 more

**Comment by s0mt0x64** [comment] 2024-01-07 11:20
I have the same issue and it's yet to be fixed 
Are the maintainers of this project still alive ??

**Comment by KeeJef** [comment] 2024-01-07 11:53
I haven't seen this issue personally, but we will look into it, no the maintainers are not dead

**Comment by d4f5409d** [comment] 2024-01-13 10:37
> Is this a new account? do you know roughly how old the previous version was before updating?

Not old at all. It was the previous v. No, it's not a new account.

**Comment by KeeJef** [comment] 2024-02-06 03:41
Try uninstalling and reinstalling, this is likely caused by a database migration from a very old version of Session to a newer version of Session which can cause unexpected issues.

**Comment by KeeJef** [comment] 2024-08-27 03:48
Closing this one for now

**Closed by KeeJef** 2024-08-27 03:48 UTC
