### ISSUE TITLE
ui:It is recommended to cancel the "+" text description, which is more concise and beautiful, thank you!

### ISSUE THREAD

**Issue by rrn21833** [oxen-io/session-android#863] opened 2022-03-27 10:38 UTC
**Code of conduct**

- [ ] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

**To reproduce**

**Screenshots or logs**

If applicable, add screenshots or logs to help explain your problem.

**Smartphone (please complete the following information):**

 - Device: [e.g. Samsung Galaxy S8]
 - OS: [e.g. Android Pie]
 - Version of Session or latest commit hash

**Additional context**

**Comment by hjubb** [comment] 2022-03-29 22:31
Is this a duplicate of #858 ?

**Comment by hjubb** [comment] 2022-04-19 01:49
closing as duplicate of #858

**Closed by hjubb** 2022-04-19 01:49 UTC
Labels: bug
