### ISSUE TITLE
URLs containing a query string are not recognized correctly in messages.

### ISSUE THREAD

**Issue by bohwaz** [oxen-io/session-android#1191] opened 2023-05-16 10:01 UTC
**Code of conduct**

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

If I post the URL `https://mydomain.tld/?article123` in a conversation, the clickable link will lead to `https://mydomain.tld/`, forgetting about the query string part.

**Comment by bemusementpark** [comment] 2023-07-13 03:41
Can't reproduce.

Possibly fixed in https://github.com/oxen-io/session-android/pull/1184 addressing https://github.com/oxen-io/session-android/issues/1119

**Closed** 2023-07-19 07:02 UTC
Labels: bug
