### ISSUE TITLE
Bug: Unread messages not prioritized 

### ISSUE THREAD

**Issue by tashijayla** [oxen-io/session-android#1148] opened 2023-04-10 09:19 UTC
**Code of conduct**

- [ ] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

When I open a chat with unread messages instead of it opening at the beginning of the unread messages it opens at the bottom of the chat

**To reproduce**

Join a group and wait until it has a large number of unread messages, then open it and you will find it's scrolled passed all the unread messages to the bottom of the chat 

**Smartphone (please complete the following information):**

 - Device: [Pixel 5]
 - OS: [Graphene OS 13 ]
 - Version of Session or latest commit hash Session 1.16.7

**Additional context**

Platform: Android
Version: 1.16.7
Summary: Viewing a chat with unread messages no longer opens at the last read message.
Current behavior: The chat starts at the latest message, as if there were no unread messages.
Previous behavior: The chat would start at the last read message.

**Comment by fracting** [comment] 2023-05-30 06:40
> Hopefully this one is reverted and fixed in the #1096 PR, it will better track unread / last read / open the conversation to where the last read message was

@0x330a 

It seems this is not fixed in #1096 PR, I've built and tested the libsession integration branch ([9a7d3a4](https://github.com/oxen-io/session-android/commit/9a7d3a45d7acd6ee1eae39bf45ff956c981fe371)) and still encountered this one.

**Comment by mpretty-cyro** [comment] 2023-06-08 02:41
> > Hopefully this one is reverted and fixed in the #1096 PR, it will better track unread / last read / open the conversation to where the last read message was
> 
> @0x330a
> 
> It seems this is not fixed in #1096 PR, I've built and tested the libsession integration branch ([9a7d3a4](https://github.com/oxen-io/session-android/commit/9a7d3a45d7acd6ee1eae39bf45ff956c981fe371)) and still encountered this one.
> 
> I can reproduce with any Community with more than 100 unread messages, I don't know if I can reproduce it with 1-1 private chat.

I'm just trying to replicate this in #1096 now, @fracting were you seeing the issue when opening a conversation with unread messages from the conversation list or just when initially joining a community? (I've been able to replicate the latter but haven't been able to cause it any other way so far)

**Comment by fracting** [comment] 2023-06-08 03:03
> @fracting were you seeing the issue when opening a conversation with unread messages from the conversation list or just when initially joining a community? (I've been able to replicate the latter but haven't been able to cause it any other way so far)

My testing setup is a combination of self built libsession integration Android + libsession integration iOS

If I remember correctly, I can reproduce only when:
a. initially joining a new community, OR
b. An android device syncs an already subscribed community from an iOS device

I'll retest and report in an hour to double check.

**Comment by fracting** [comment] 2023-06-08 03:40
> a. initially joining a new community, OR 
> b. An android device syncs an already subscribed community from an iOS device

I can't reproduce with **opening a conversation with unread messages from the conversation list**;
I can confirm **a. initially joining a new community**;
I am not able to retest **b. An android device syncs an already subscribed community from an iOS device** at the moment because my local build fails after some mistake I made.

I remember I might be able to reproduce it with `1-1` or closed group when cross-device syncing is enable, but I'm not able to test at the moment because my build failure.

**Comment by mpretty-cyro** [comment] 2023-06-08 03:48
> > a. initially joining a new community, OR
> > b. An android device syncs an already subscribed community from an iOS device
> 
> I can't reproduce with **opening a conversation with unread messages from the conversation list**; I can confirm **a. initially joining a new community**; I am not able to retest **b. An android device syncs an already subscribed community from an iOS device** at the moment because my local build fails after some mistake I made.
> 
> I remember I might be able to reproduce it with `1-1` or closed group when cross-device syncing is enable, but I'm not able to test at the moment because my build failure.

You are amazing, thanks!

I'll try to replicate **b** on my side as well and will post here once I've been able to push a fix to that branch - I expect if you are seeing the same issue in one-to-one and group conversations then it'll be the same as the cause of **b** but I'll double check those just to be safe 👍

**Comment by fracting** [comment] 2023-06-08 04:20
Update:



1. I can't reproduce with **opening a conversation with unread messages from the conversation list**;

2. I can reproduce with **a. initially joining a new community**;

Note that there is a subtle behaviour difference between Session iOS and Session Android:
* On Session iOS, when initially joining a new community, the community will stay in the conversation list, the user has to manually click the conversation entry to enter the community thread.
* On Session Android, when initially joining a new community, Session will open the community thread automatically for the user. I can't say which behaviour is better but I am used to the Session iOS behaviour btw. When Session Android automatically opens the newly joint community for me, there is no messages initially, if I stay in the community thread, it will reset unread count to 0 after fetching the last 100 messages. However, if I manually leave the community thread immediately before fetching messages, then manually re-enter the community thread after finishing fetching the last 100 messages, then the unread count will not be reset to 0.

3. I fixed my local builds, but I am not able to reproduce **b. An android device syncs an already subscribed community from an iOS device** , neither `1-1` or closed group, with or without cross-device syncing. My memory might be incorrect, I might confuse my testing result on the Android prerelease with testing result on my local built and created an hybrid incorrect memory, I regret not taking notes for my testing result, sorry for the confusing, please ignore them if you can't reproduce as well.

**Comment by mpretty-cyro** [comment] 2023-06-08 05:46
> Note that there is a subtle behaviour difference between Session iOS and Session Android:
> 
> * On Session iOS, when initially joining a new community, the community will stay in the conversation list, the user has to manually click the conversation entry to enter the community thread.
> * On Session Android, when initially joining a new community, Session will open the community thread automatically for the user. I can't say which behaviour is better but I am used to the Session iOS behaviour btw.

Yea I believe the Android behaviour was the one we wanted (the User Config PR for iOS seems to be doing this for me so I guess I updated it in there 🤷) - I think the rationale was that if a user joins a community the majority of the time they are doing so because they want to immediately view the content

> When Session Android automatically opens the newly joint community for me, there is no messages initially, if I stay in the community thread, it will reset unread count to 0 after fetching the last 100 messages. However, if I manually leave the community thread immediately before fetching messages, then manually re-enter the community thread after finishing fetching the last 100 messages, then the unread count will not be reset to 0.

Yep this is what I'm seeing as well - I'm looking into a couple of other small issues with the `1.16.8` release first but will be jumping back on debugging this after

> 3. I fixed my local builds, but I am not able to reproduce **b. An android device syncs an already subscribed community from an iOS device** , neither `1-1` or closed group, with or without cross-device syncing. My memory might be incorrect, I might confuse my testing result on the Android prerelease with testing result on my local built and created an hybrid incorrect memory, I regret not taking notes for my testing result, sorry for the confusing, please ignore them if you can't reproduce as well.

Ok good to know, and no worries this has all been incredibly helpful - I'll still do some testing on my side to make sure this isn't an issue for one-to-one and group conversations just in case

**Comment by mpretty-cyro** [comment] 2023-06-09 00:32
So the "initial join" case seems to primarily be due to how the conversation list in Android renders - since there are no messages initially it starts with a scroll offset of `0` (ie. it's scrolled to the "top" of the list) but Android has a `reverseLayout` flag which makes the list add items at the bottom of the screen up where a scroll offset of `0` is the bottom-most point of the list

Once the messages get loaded in they end up getting added from most-recent (at the bottom of the screen) backwards, this results in the user essentially reading the most recent message immediately since that's the part of the list already on the screen

I'll look to push up my fix for the "initial join" case a bit later today (the logic currently assumes that `0` is at the bottom of the screen so I need to go through the code and try to remove this assumption - would be nice if I didn't introduce other bugs by doing this 😅)

I haven't been able to replicate the other case yet and still have a few more edge-cases I can think of to test

**Comment by KeeJef** [comment] 2023-07-21 07:09
This should be resolved on Android as of 1.17.0

**Closed by KeeJef** 2023-07-21 07:09 UTC
Labels: bug
