### ISSUE TITLE
(Feature request) Background wallpaper for chats

### ISSUE THREAD

**Issue by hardBSDk** [oxen-io/session-android#757] opened 2021-10-05 08:54 UTC
https://github.com/oxen-io/session-desktop/issues/1960

**Comment by tashijayla** [comment] 2021-11-09 14:30
That's one thing I would really love.👍
But let me add another idea?, What about if  a chat background could be automatically created using the colours from your contacts profile photo ❣️

**Comment by KeeJef** [comment] 2022-12-16 04:43
Closing as duplicate of #394

**Closed by KeeJef** 2022-12-16 04:43 UTC
Labels: feature-request
