### ISSUE TITLE
Messages with self-destruct not deleted from server 

### ISSUE THREAD

**Issue by gabrielepanciotti** [oxen-io/session-android#1052] opened 2022-12-03 10:27 UTC
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

By connecting the same account on multiple devices I noticed that although I had set the self-destruct timer on all chats, even though on the smartphone I no longer had any messages present in the chats because they were deleted, when I went to log in via desktop I found all messages sent and received up to that point.
Over time then it resynchronized with the other device, deleting the messages that were not supposed to be there, but today going to connect yet another smartphone, I again found all the messages that were supposed to be deleted.
In some chats for example I set the timer for 1 day on November 19, on November 20 I sent a message, the next day from the sent device it was deleted.
Today Dec. 3 I logged into the same account but from a new device and I can see the message sent on Nov. 20 and deleted the next day.
In addition, another bug I encountered was that by logging in with another account to a device where another account had been before, all the chats from the old account appeared to me, but they were not from the new account.
These seem like two pretty serious bugs to me, I don't know how no one has noticed them so far, shouldn't you also delete messages from your server once the self-destruct timer has expired?

**Comment by hjubb** [comment] 2022-12-05 22:57
Yes the self-destruct messages were originally a client-side only implementation, this is currently being worked on to make it work across all devices and participants and enable server deletion as well. By design the server will only hold messages for 14 days so that multiple devices can synchronise the state. I believe this is a duplicate of a few other issues mentioned, but you can follow the progress of the new self-destructing messages here https://github.com/oxen-io/session-android/pull/1014

**Closed by hjubb** 2022-12-05 22:57 UTC
Labels: bug

**Comment by gabrielepanciotti** [comment] 2022-12-21 10:32
All right thank you for your answer. The problem is that the automatic deletion from the server after 14 days doesn't work either, I still have messages from November 23, it's been more than 14 days, how is it possible that I still see them? Despite the fact that I even entered the one week timer

**Comment by hjubb** [comment] 2023-01-09 04:49
It might have not been enabled or recognised in the send side before the messages were sent or the deletion time was set. Another possibility, because the message deletion is client-side and done after opening a conversation, is that maybe the messages weren't read so never got deleted? Either way they should only exist on the device after that point
