### ISSUE TITLE
Touch (copy, open etc) pop up doesn't appear [BUG] 

### ISSUE THREAD

**Issue by tdpo2** [oxen-io/session-android#1469] opened 2024-04-24 17:19 UTC
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

With some users touch doesn't work to open menu for copy, delete, open url...

### Expected Behavior

To work as it should with other users.

### Steps To Reproduce

Select a new person to have a conversation with and popup menu won't appear...

### Android Version

android 13 / doesn't really matter 

### Session Version

1.18. version (latest)

**Comment by KeeJef** [comment] 2024-06-03 08:52
Curious if this happened after a specific URL was sent into the chat? If so might be related to this ticket https://github.com/oxen-io/session-android/issues/1444

**Comment by bemusementpark** [comment] 2024-06-04 02:19
Yeah, it's probably the same issue, sometimes we can't draw the message to Bitmap for some reason, which shouldn't prevent us from showing the menu, but it does.

**Comment by KeeJef** [comment] 2024-08-16 03:29
Closing as this is likely a duplicate of #1444 which is now resolved

**Closed by KeeJef** 2024-08-16 03:29 UTC
Labels: bug
