### ISSUE TITLE
Can't restore conversations properly

### ISSUE THREAD

**Issue by SzBenedek2006** [oxen-io/session-android#1036] opened 2022-11-05 20:55 UTC
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

Restored my account with recovery key.

2 of my contacts (and the messages in these conversations) completely dissapeared from my phone (android client), but present on my laptop and pc (both linux clients)
I can send messages to them, because I have their session id, but I can't see their name or previous messages.

**To reproduce**

Restore your account with your recovery phrase.

**Smartphone:**

 - Samsung Galaxy A52 5G
 - Android 12
 - Version 1.16.1

**Additional context**

The last messages were sent in a long time ago. The conversation may got deleted on the nodes? Is that possible?

**Comment by 0x330a** [comment] 2022-11-07 00:48
This is by design, for privacy reasons the nodes that store messages don't hold more than 2 weeks worth of content as a buffer for when devices are offline, but give enough time that you should still receive messages in that two week window when you are back online

**Comment by hjubb** [comment] 2022-11-08 04:40
Yep closing this one as it is the intended functionality, you can read about it in the FAQs and any other questions you may have
https://getsession.org/faq

**Closed by hjubb** 2022-11-08 04:40 UTC
Labels: bug
