### ISSUE TITLE
[Bug] Note to Self shows wrong icon on chat screen

### ISSUE THREAD

**Issue by rsatenza** [oxen-io/session-android#993] opened 2022-10-03 15:22 UTC
- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Note to Self shows 3rd character of user's session ID as it's icon (except in search)

### Steps to reproduce
- Click search 🔍
- Click Note to Self (which have a bookmark icon🔖)

**Actual result:**
Icon changes to 3rd character of user's session ID

**Expected result:**
Shows correct icon (i.e. of a bookmark)

**Session version:** 1.15.4

Related to #668

**Comment by tashijayla** [comment] 2022-10-05 12:33
Agreed not the best design 👍

**Comment by KeeJef** [comment] 2022-12-19 02:48
Is this still occurring? I am unable to reproduce, i either see the bookmark or my profile image.

**Comment by KeeJef** [comment] 2023-02-07 06:09
Looks more than likely that this has been fixed, closing for now

**Closed by KeeJef** 2023-02-07 06:09 UTC
