### ISSUE TITLE
Media received not displaying in chat

### ISSUE THREAD

**Issue by shrimprugbysnowowl** [oxen-io/session-android#747] opened 2021-09-28 22:29 UTC
**Code of conduct**

- [ x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

The image or gif sent by another user does not appear inline in the main chat.  The received message does not show any content.  A thumbnail can be seen of the image or gif when the message is quoted.

**To reproduce**

Have another user send an image or a gif in a closed or open group.  I've had the issue occur in both group types.  The issue does not occur consistently, but the image/gif doesn't appear more often than it appears.

**Screenshots**

Screenshot No. 1
![de4ec774-d9b3-4ec3-94d5-375d7a448fb6](https://user-images.githubusercontent.com/59341190/135172530-77f0b90c-9b1d-4a58-9688-42f1e7830a94.png)

Screenshot No. 2
![e0f69bb5-06e7-4249-b36b-154211368451](https://user-images.githubusercontent.com/59341190/135172549-bfa35571-1831-40f0-baaf-487138bfa7fe.png)

**Smartphone:**

 - Device: Google Pixel 4a
 - OS: Android 11 (CalyxOS v2.9.0)
 - Version of Session or latest commit hash: v1.11.9 (2215)

**Additional context**

Will provide upon request.

**Comment by hjubb** [comment] 2021-10-01 04:00
it would be interesting to know whether or not the messages themselves were also sent on android or on a different platform if possible, but otherwise will keep an eye out for this to reproduce and fix

**Comment by shrimprugbysnowowl** [comment] 2021-10-01 13:36
The senders have been from iOS and Linux platforms.  This issue has also been brought up by others in the Session open group, but I don't know those experiences.  I will watch for more missing images/docs and update as I can.

**Comment by hjubb** [comment] 2021-10-02 01:37
thanks, I'll be looking into this :+1:

**Comment by Sepero** [comment] 2021-10-02 04:42
Maybe I can help shine some light on this bug. When someone sends an image as reply, then the image doesn't appear. Only a reply with an Empty Gap Space underneath.
![Screenshot_20211002-113354__01](https://user-images.githubusercontent.com/1575546/135703761-a277ecb3-1e33-4e33-a35c-77fd6e7d412f.jpg)

**Comment by hjubb** [comment] 2021-10-02 04:57
After testing it looks like it's to do with a disparity between the client implementations, in particular the desktop client (and maybe iOS) lets you reply to messages with images but the Android client had limitations on that, so we are treating all replies as not containing media. I'll just add in the ability to support media with replies first and all the current messages should render fine then afterwards double check and add support to make sure that you can make replies while attaching media

**Comment by Sepero** [comment] 2021-10-06 08:27
In my humble opinion, the implementation of sending text and image in a single message is riddled with problems. When someone writes a long message with an image, it does a truncation that can only be seen by clicking the text. It may be worth considering dropping it in the future, in favor of keeping images and text separate.

**Comment by shrimprugbysnowowl** [comment] 2021-10-15 16:14
Now the issue seems to be isolated (at least for me) when another person adds media while replying to a post.

![977ae967-3f69-4ae4-b3d5-809684a3a2d1](https://user-images.githubusercontent.com/59341190/137519743-b4721426-9604-4cf4-95df-493eb75073b4.png)

**Comment by KeeJef** [comment] 2022-12-16 04:38
Assuming this is now fixed, please reopen if this is still and issue

**Closed by KeeJef** 2022-12-16 04:38 UTC
Labels: bug

**Comment by shrimprugbysnowowl** [comment] 2022-12-16 05:21
Though not the purpose of the original issue here, #775 seems to pertain to an issue replying to a post with media (media doesn't appear). Is that feature planned? Or worth keeping this or #775 (or other) open to track?

**Comment by Sepero** [comment] 2022-12-18 05:41
Thank you for cleaning up and closing out old bugs KeeJef. I do not appear to experience this big anymore
