### ISSUE TITLE
[Not Sure] Sessions current state (1.12.3)

### ISSUE THREAD

**Issue by XeoAzar** [oxen-io/session-android#843] opened 2022-02-09 11:58 UTC
I really hope this is seen by a session team member and insights change. Session in it's current state (1.12.3) is almost perfect (from a user perspective I mean, I understand there's still alot of work to be done behind the scenes) for me and everyone I've spoken too who uses session this includes but is not limited too friends, work colleges and people I've met on discord (I'm always trying to convince people to download session on there phone) but the most common criticisms I hear are.

1. The file size limit is too low to send videos (I think a sensible size would be 100mb) (BONUS: include in session a way to compress any video you send to 100mb so you don't have to think or worry about if a video is too large to be sent or not)

2. On certain operating systems like grapeneos, real time notifications do not work/are delayed, if possible fix or at least give the option to users to have session keep running in the background regardless of power drain

3. (This one is for me) please please please please please for the sake of my sanity include beta/pre release versions of session on the fdroid repo or make a channel for it so I don't have to keep coming back to the GitHub, I know in the future when calls are in the full release this won't matter so much but I still think it should be an option 

I hope I haven't Posted this in the wrong place, I just did not know where else to post it, I hope that session push these changes to there app as I believe this would remove the barrier to entry for less "tech savvy" people.

My session ID:
0592fc58d55c381d4cc00d8b19f737c803549c5f68509f51ff9a7c155a7e0bdf47

**Comment by XeoAzar** [comment] 2022-02-09 12:07
Does anyone know the current file size limit? I can't find any information about it anywhere

**Comment by hjubb** [comment] 2022-02-17 06:04
Thanks @XeoAzar, a few of these issues are longer term and being set up to be enabled through ongoing development like the file size limits, I think at the moment the restriction is that the files need to fit inside ~10mb before the overhead of encrypting for each hop along the way, you might lose up to 1/3rd of that unfortunately but we are trying to look at ways to enable greater limits on those as the technologies mature.

Regarding the realtime notifications, the idea of maintaining a persistent foreground service to fetch quicker than the background job's frequency restrictions currently provides would be great, at the moment it's probably restricted on the same kind of issues that the onion requests would face and require some sort of polling but I'm sure in the future there will be ways to avoid this. As it stands though there's probably the ability to have a foreground service that would be able to run in the same function as the background polling, only a lot more frequently. The performance and battery / network impacts would have to be considered I guess, maybe it'd need to be configurable in some way in case people wanted it to poll somewhere in between instant and every 15 minutes or so.

The beta and pre-release session on fdroid could be achievable, the current experience for a single repo with a beta release might trigger a 'new update' for everyone including people that don't want to update to beta versions but there might be some way around this whether it's a separate repo or if fdroid's repo config / build tools let you specify if something is beta. If you have any examples or info on the way that other apps do this I'd gladly take a look to see if we can do something similar :+1: 

Thanks for the feedback, it's really helpful to know the things that people value the most to help shape what to try to improve in priority!

**Comment by XeoAzar** [comment] 2022-02-20 00:37
@hjubb 

Im pretty sure the fdroid situation could be fixed easily buy having 2 versions of session on your repo like how tor have multiple different applications in there repo, I personally would suggest keeping it simple one channel for the beta and one for the stable like how there is on your GitHub. 

For the notifications I would love to have the option to choose between "instant" or 15 mins or so that would be real nice and I'm sure others will agree 

PS: pls add a 48 hour timer to chats myself and everyone else will love you for it <3 

And please keep up the amazing work, you guys don't get enough credit, your building a messenger for the people and you are making a huge difference, your work is protecting human rights and saving life's.

**Comment by KeeJef** [comment] 2022-12-16 05:23
Closing for duplicate of #169 and #267, Please reopen the prerelease F-droid issue as a separate issue so we can track it, it is something i think we would be interested in

**Closed by KeeJef** 2022-12-16 05:23 UTC
Labels: feature-request
